name: Build & deploy static site to GitHub Pages

on:
  push:
    branches: [main]          # every push to main kicks off a new build

permissions:
  contents: write             # so the action can create/update gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages        # the branch GitHub Pages will serve
          publish_dir: ./out              # Next.js export output
          force_orphan: true              # replace the branch each deploy
          cname: maximmarchal.nl          # recreates the CNAME for you
